// Generated by C# language instantiator generator!
// Don't modify, but you can delete and regenerate any time!

namespace Examples.M2;

using LionWeb.Core.M3;

public static class WithEnum
{
    public static readonly Language Instance = new(
        "RkXMUe9zMRUQpw3bzQjSbBX6ju1a0UplEYsVa799WPQ",
        "WithEnum",
        "WithEnum",
        "1"
    );

    static WithEnum()
    {
        var EnumHolder = Instance.Concept("PHrmcBTHnKIQD5HKKaWjhGp2U8Ndc99uZ0JftEqCjms", "EnumHolder", "EnumHolder");
        var MyEnum = Instance.Enumeration("uLnvTaBlWPqfYfLjfN9HG9Qjt4VQHhFVRorDLFeYhZE", "MyEnum", "MyEnum");

        EnumHolder.Property("kzHwP_f-H6_UOSDM4Au_XDc-Jb-sIcxw3vu7XvqotgU", "enumValue", "enumValue").OfType(MyEnum);

        MyEnum.EnumerationLiteral("0euWZGmWfx0iPC66yajzWqv3gIv--pvo55hqY82nREc", "lit1", "literal1");
        MyEnum.EnumerationLiteral("ArZRq3V1eIqmZBN88UlVbeRFfp3YVf-_JMd9-s64Yjg", "lit2", "literal2");
    }
}
